import * as THREE from './vendor/three.module.js';
import { RoomEnvironment } from './vendor/RoomEnvironment.js';
import { OrbitControls } from './vendor/OrbitControls.js';
import { patchGeometry, bendAt } from './patch-model.js';
const $=s=>document.querySelector(s);
const LANG=new URLSearchParams(location.search).get('lang')==='en'?'en':'es';
document.documentElement.lang=LANG;
const T={
 es:{title:'Dentro de CHEEKZ — biogradix',metaDesc:'Descubre cómo trabajan juntas las tres capas del parche bucal CHEEKZ.',headerTitle:'CÓMO FUNCIONA CHEEKZ',headerNote:'TRES CAPAS. UN PROPÓSITO.',eyebrowIntro:'EL PARCHE BUCAL',h1:'Dentro de<br><em>CHEEKZ.</em>',introP:'Tres capas trabajando juntas.<br>Descubre qué hace cada una.',listHead:'LAS TRES CAPAS',showAll:'Mostrar todo',isolate:'Aislar componente',showAllComponents:'Mostrar todos los componentes',asideFootA:'01 — 03',asideFootB:'Toca una capa para inspeccionar',assembled:'VISTA ENSAMBLADA',exploded:'VISTA EXPLOSIONADA',loading:'Preparando el parche…',autoRotate:'Rotación auto',autoRotateTitle:'Activar rotación automática',reset:'Reiniciar vista',resetTitle:'Reiniciar cámara y componentes',caption:'ARRASTRA PARA GIRAR <span>·</span> SCROLL PARA ZOOM <span>·</span> CLIC PARA INSPECCIONAR',explHeadEyebrow:'VISTA EXPLOSIONADA',explHeadH2:'Descubre cada capa.',explodeBtn:'Explorar capas <span>↗</span>',explodePatch:'Explosionar parche <span>↗</span>',assemblePatch:'Ensamblar parche <span>↙</span>',rangeA:'Ensamblado',rangeB:'Explosionado',component:'COMPONENTE',footA:'CHEEKZ™ <span class="separator">/</span> Parche bucal de tres capas',footB:'Hecho para el interior de tu mejilla.',closeDetail:'Cerrar detalles del componente',inspect:'Inspeccionar',show:'Mostrar',canvasAria:'Parche CHEEKZ en 3D. Arrastra para orbitar, haz scroll para acercar, haz clic en un componente para inspeccionarlo. Los botones de componentes permiten selección por teclado.',fallbackAlt:'Parche CHEEKZ de esquinas redondeadas con centro crema y borde pálido más ancho',fallbackP:'Explora las tres capas usando el panel.<br><small>El 3D interactivo requiere un navegador con WebGL habilitado.</small>',sceneTag:'CHEEKZ™ / TD-IntelGel™'},
 en:{title:'Inside CHEEKZ — biogradix',metaDesc:'Discover how the three layers of the CHEEKZ buccal patch work together.',headerTitle:'HOW CHEEKZ WORKS',headerNote:'THREE LAYERS. ONE PURPOSE.',eyebrowIntro:'THE BUCCAL PATCH',h1:'Inside<br><em>CHEEKZ.</em>',introP:'Three layers working together.<br>Discover what each one does.',listHead:'THE THREE LAYERS',showAll:'Show all',isolate:'Isolate component',showAllComponents:'Show all components',asideFootA:'01 — 03',asideFootB:'Click a layer to inspect',assembled:'ASSEMBLED VIEW',exploded:'EXPLODED VIEW',loading:'Preparing the patch…',autoRotate:'Auto-rotate',autoRotateTitle:'Toggle automatic rotation',reset:'Reset view',resetTitle:'Reset camera and components',caption:'DRAG TO ROTATE <span>·</span> SCROLL TO ZOOM <span>·</span> CLICK TO INSPECT',explHeadEyebrow:'EXPLODED VIEW',explHeadH2:'Discover each layer.',explodeBtn:'Explore layers <span>↗</span>',explodePatch:'Explode patch <span>↗</span>',assemblePatch:'Assemble patch <span>↙</span>',component:'COMPONENT',footA:'CHEEKZ™ <span class="separator">/</span> Three-layer buccal delivery',footB:'Made for the inside of your cheek.',closeDetail:'Close component details',inspect:'Inspect',show:'Show',canvasAria:'3D CHEEKZ patch. Drag to orbit, scroll to zoom, click a component to inspect. Component buttons offer keyboard selection.',fallbackAlt:'CHEEKZ rounded-square patch with a cream center and wider pale border',fallbackP:'Explore the three layers using the panel.<br><small>Interactive 3D requires a browser with WebGL enabled.</small>',rangeA:'Assembled',rangeB:'Exploded',sceneTag:'CHEEKZ™ / TD-IntelGel™'}
}[LANG];

const data=[
 {name:LANG==='es'?'Péptidos liofilizados estabilizados':'Stabilized Lyophilized Peptides',sub:LANG==='es'?'Hidrogel con péptidos':'Peptide-containing hydrogel',color:0xe5816b,base:.35,offset:2.05,scale:1,thick:.14,text:LANG==='es'?'Las partículas de péptido están contenidas en esta capa de hidrogel. Se adhiere a la mucosa bucal — el interior de tu mejilla — y está diseñada para elongar suavemente el tejido, aumentando la superficie y la permeabilidad para la entrega.':'Peptide particles are contained within this hydrogel layer. It adheres to the buccal mucosa—the inside of your cheek—and is designed to gently elongate the tissue, increasing the surface area and permeability for delivery.'},
 {name:'TD-IntelGel™',sub:LANG==='es'?'Matriz protectora':'Protective matrix',color:0xb6d7e1,base:.081,offset:1.04,scale:1.07,thick:.25,text:LANG==='es'?'La matriz ayuda a mantener la integridad de los péptidos dentro del parche, dando soporte al sistema de entrega mientras permanece contra el interior de tu mejilla.':'The matrix helps maintain the integrity of the peptides within the patch, supporting the delivery system as it sits against the inside of your cheek.'},
 {name:'Muco-SmartSeal™',sub:LANG==='es'?'Sello antifuga · capa base':'Zero-leakage seal · base layer',color:0xecebe6,base:.02,offset:0,scale:1.34,thick:.045,text:LANG==='es'?'La base más ancha se extiende más allá de las dos capas activas y forma un borde sellador protector. Está diseñada para crear un sello antifuga: mantiene la saliva lejos del sistema de entrega de péptidos y evita que los péptidos escapen hacia la saliva, donde se degradarían.':'The wider base extends beyond both active layers to form a protective sealing border. It is designed to create a zero-leakage seal, helping keep saliva away from the peptide delivery system and preventing peptides from escaping into saliva, where they would otherwise be degraded.'}
];
(function(){document.title=T.title;const md=document.querySelector('meta[name=description]');if(md)md.setAttribute('content',T.metaDesc);
 const setHTML=(sel,html)=>{const el=document.querySelector(sel);if(el)el.innerHTML=html};const setText=(sel,txt)=>{const el=document.querySelector(sel);if(el)el.textContent=txt};
 setText('.header-title',T.headerTitle);setText('.header-note',T.headerNote);setText('.intro .eyebrow',T.eyebrowIntro);setHTML('.intro h1',T.h1);setHTML('.intro p',T.introP);setText('.list-head span',T.listHead);setText('#showAll',T.showAll);setText('#isolate',T.isolate);
 const foot=document.querySelectorAll('.aside-foot span');if(foot[0])foot[0].textContent=T.asideFootA;if(foot[1])foot[1].textContent=T.asideFootB;
 setText('#viewTitle',T.assembled);setText('#loading',T.loading);setText('#rotate',T.autoRotate);const rb=document.querySelector('#rotate');if(rb)rb.title=T.autoRotateTitle;setText('#reset',T.reset);const rs=document.querySelector('#reset');if(rs)rs.title=T.resetTitle;
 setHTML('.stage-caption',T.caption);setText('.explosion-heading .eyebrow',T.explHeadEyebrow);setText('.explosion-heading h2',T.explHeadH2);setHTML('#explode',T.explodeBtn);
 const rr=document.querySelectorAll('.range-row label, .range-row > span');const rl=document.querySelector('.range-row label');if(rl)rl.textContent=T.rangeA;const rspan=document.querySelector('.range-row > span:not(.separator)');if(rspan)rspan.textContent=T.rangeB;
 const fs=document.querySelectorAll('footer > span');if(fs[0])fs[0].innerHTML=T.footA;if(fs[1])fs[1].textContent=T.footB;
 const cd=document.querySelector('#closeDetail');if(cd)cd.setAttribute('aria-label',T.closeDetail);
})();
let selected=-1,isolated=false,target=0,amount=0,auto=false;const visible=data.map(()=>true);let scene,camera,renderer,controls,groups=[],meshes=[],stage;
const eye='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/></svg>';
$('#components').innerHTML=data.map((d,i)=>`<div class="component" data-index="${i}"><button class="select" aria-label="${T.inspect} ${d.name}"><span class="num">0${i+1}</span><span><strong>${d.name}</strong><small>${d.sub}</small></span></button><button class="visibility" aria-label="${T.show} ${d.name}" aria-pressed="true">${eye}</button></div>`).join('');
function select(i){selected=i;$('#detail').hidden=i<0;document.querySelectorAll('.component').forEach((el,j)=>el.classList.toggle('selected',i===j));if(i>=0){$('#detailIndex').textContent=`${T.component} 0${i+1} / 03`;$('#detailName').textContent=data[i].name;$('#detailText').textContent=data[i].text;$('#isolate').textContent=isolated?T.showAllComponents:T.isolate;}updateVisibility();}
function updateVisibility(){groups.forEach((g,i)=>{g.visible=visible[i]&&(!isolated||i===selected);g.traverse(o=>{if(o.isMesh&&o.material.emissive){o.material.emissive.setHex(i===selected?data[i].color:0);o.material.emissiveIntensity=i===selected?.035:0;}})});document.querySelectorAll('.visibility').forEach((e,i)=>e.setAttribute('aria-pressed',String(visible[i])));}
document.querySelectorAll('.component').forEach((el,i)=>{el.querySelector('.select').onclick=()=>{visible[i]=true;select(i)};el.querySelector('.visibility').onclick=()=>{visible[i]=!visible[i];updateVisibility()}});
$('#closeDetail').onclick=()=>{isolated=false;select(-1)};$('#showAll').onclick=()=>{visible.fill(true);isolated=false;select(selected)};$('#isolate').onclick=()=>{isolated=!isolated;select(selected)};
function spread(v){target=Number(v)/100;$('#spread').value=v;$('#percent').textContent=Math.round(v)+'%';$('#viewTitle').textContent=target>.01?T.exploded:T.assembled;$('#explode').innerHTML=target>.5?T.assemblePatch:T.explodePatch;}
$('#spread').oninput=e=>spread(e.target.value);$('#explode').onclick=()=>{isolated=false;updateVisibility();spread(target>.5?0:100)};
$('#rotate').onclick=()=>{auto=!auto;$('#rotate').setAttribute('aria-pressed',String(auto));if(controls)controls.autoRotate=auto};
$('#reset').onclick=()=>{spread(0);isolated=false;visible.fill(true);select(-1);auto=false;$('#rotate').setAttribute('aria-pressed','false');if(controls){controls.autoRotate=false;controls.reset()}};
function microTexture(fibrous=false){
 const size=1024, pixels=new Uint8Array(size*size*4);let state=23;
 const rnd=()=>{state=(state*16807)%2147483647;return(state-1)/2147483646};
 for(let y=0;y<size;y++)for(let x=0;x<size;x++){const i=(y*size+x)*4;
 const grain=(rnd()-.5)*36;const fiber=fibrous?Math.sin(x*.4+Math.sin(y*.035)*4)*10+Math.sin(y*.8+x*.04)*7:Math.sin(x*.025)*Math.sin(y*.031)*8;
 const v=Math.max(0,Math.min(255,145+grain+fiber));pixels[i]=pixels[i+1]=pixels[i+2]=v;pixels[i+3]=255;}
 const texture=new THREE.DataTexture(pixels,size,size,THREE.RGBAFormat);texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.magFilter=THREE.LinearFilter;texture.minFilter=THREE.LinearMipmapLinearFilter;texture.generateMipmaps=true;texture.needsUpdate=true;texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());return texture;
}
function init(){stage=$('#stage');scene=new THREE.Scene();scene.background=new THREE.Color(0xede8e0);scene.fog=new THREE.Fog(0xede8e0,16,35);camera=new THREE.PerspectiveCamera(34,1,.1,60);camera.position.set(5.7,6.2,7.6);renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;stage.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label',T.canvasAria);renderer.domElement.setAttribute('role','img');controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.75,0);controls.enableDamping=true;controls.minDistance=3.5;controls.maxDistance=19;controls.maxPolarAngle=Math.PI*.48;controls.autoRotateSpeed=.55;controls.enablePan=false;controls.saveState();scene.add(new THREE.HemisphereLight(0xf5f1eb,0x746b5e,1.5));const key=new THREE.DirectionalLight(0xfff3e1,2.8);key.position.set(-3,9,4);key.castShadow=true;key.shadow.mapSize.set(4096,4096);key.shadow.camera.left=-7;key.shadow.camera.right=7;key.shadow.camera.top=7;key.shadow.camera.bottom=-7;key.shadow.normalBias=.025;key.shadow.bias=-.0001;key.shadow.radius=4;scene.add(key);const rim=new THREE.DirectionalLight(0xe1e6df,1.2);rim.position.set(2,4,-5);scene.add(rim);const fill=new THREE.DirectionalLight(0xf5f1eb,1.3);fill.position.set(5,2,5);scene.add(fill);
const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();const env=pmrem.fromScene(room,.045);scene.environment=env.texture;scene.environmentIntensity=.55;room.dispose();pmrem.dispose();
const plinth=new THREE.Mesh(new THREE.CylinderGeometry(2.55,2.60,.16,192),new THREE.MeshStandardMaterial({color:0xe0d9ce,roughness:.65}));plinth.position.y=-.10;plinth.receiveShadow=true;plinth.castShadow=true;scene.add(plinth);const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:0xede8e0,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.22;floor.receiveShadow=true;scene.add(floor);
let seed=124;const random=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};
const fine=microTexture();
data.forEach((d,i)=>{
 const group=new THREE.Group();group.rotation.y=-.28;scene.add(group);groups.push(group);
 const finishes=[
  {roughness:.23,bumpScale:.0016,clearcoat:.8,clearcoatRoughness:.15,transmission:.18,thickness:.14,ior:1.39,attenuationColor:new THREE.Color(0xe6826b),attenuationDistance:.8},
  {roughness:.14,bumpScale:.001,clearcoat:1,clearcoatRoughness:.10,transmission:.66,thickness:.25,ior:1.34,attenuationColor:new THREE.Color(0xb4dce8),attenuationDistance:1.5},
  {roughness:.34,bumpScale:.0012,clearcoat:.42,clearcoatRoughness:.24,transmission:.10,thickness:.045,ior:1.40,iridescence:.12,iridescenceIOR:1.3,iridescenceThicknessRange:[80,160]}
 ];
 const mat=new THREE.MeshPhysicalMaterial({color:d.color,metalness:0,bumpMap:fine,side:THREE.DoubleSide,...finishes[i]});
 const mesh=new THREE.Mesh(patchGeometry(d.scale,d.thick,i===2),mat);mesh.userData.index=i;mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);meshes.push(mesh);
 if(i===0){
  // Embedded inclusions stay inside this layer during every interaction.
  const granules=new THREE.InstancedMesh(new THREE.SphereGeometry(.009,16,12),new THREE.MeshPhysicalMaterial({color:0xf7b59d,roughness:.3,transparent:true,opacity:.4}),650);
  const dummy=new THREE.Object3D();for(let k=0;k<650;k++){const x=(random()-.5)*2.42,z=(random()-.5)*1.56;dummy.position.set(x,bendAt(x,z)+d.thick*(.22+random()*.66),z);dummy.scale.setScalar(.5+random()*1.4);dummy.updateMatrix();granules.setMatrixAt(k,dummy.matrix)}granules.userData.index=i;group.add(granules);meshes.push(granules);
 }
 if(i===1){
  // Clear inclusions belong to the matrix, never a fourth selectable layer.
  const inclusions=new THREE.InstancedMesh(new THREE.SphereGeometry(1,20,14),new THREE.MeshPhysicalMaterial({color:0xd9edf1,roughness:.08,metalness:0,clearcoat:1,ior:1.08}),110);
  const dummy=new THREE.Object3D();let k=0;
  while(k<110){const x=(random()-.5)*2.9,z=(random()-.5)*1.94;
   if(Math.pow(Math.abs(x)/(1.50*d.scale),2/.72)+Math.pow(Math.abs(z)/(1.03*d.scale),2/.72)>.88)continue;
   const r=.013+random()*.031;dummy.position.set(x,bendAt(x,z)+r+.025+random()*(d.thick-2*r-.05),z);dummy.scale.set(r*(.75+random()*.55),r*.70,r);dummy.rotation.set(random(),random(),random());dummy.updateMatrix();inclusions.setMatrixAt(k++,dummy.matrix);
  }
  inclusions.userData.index=i;group.add(inclusions);meshes.push(inclusions);
 }
 group.position.y=d.base;
});
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down;renderer.domElement.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(meshes,false).filter(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent}return true});if(hits.length)select(hits[0].object.userData.index)});
new ResizeObserver(()=>{const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.fov=w<500?39:32;camera.updateProjectionMatrix()}).observe(stage);$('#loading').remove();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let last=0;function frame(t){requestAnimationFrame(frame);if(document.hidden)return;const dt=Math.min((t-last)/1000,.05);last=t;amount=reduced?target:THREE.MathUtils.damp(amount,target,5,dt);groups.forEach((g,i)=>{g.position.y=data[i].base+data[i].offset*amount});controls.target.y=.75+amount*.5;controls.update();renderer.render(scene,camera)}requestAnimationFrame(frame);}
try{init()}catch(e){console.error(e);$('#loading').innerHTML='<img class=\"fallback-photo\" src=\"assets/patch-photo.png\" alt=\"'+T.fallbackAlt+'\"><p>'+T.fallbackP+'</p>';$('#loading').className='fallback';}
select(0);
const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(console.warn)}catch(e){console.warn(e)}};
register({name:'inspect_patch_component',description:'Select a component in the patch atlas, optionally isolating it.',inputSchema:{type:'object',properties:{component:{type:'integer',minimum:1,maximum:3},isolate:{type:'boolean'}},required:['component'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Number.isInteger(input.component)||input.component<1||input.component>3||(input.isolate!==undefined&&typeof input.isolate!=='boolean'))throw new Error('Choose a component from 1 to 3.');isolated=input.isolate??false;visible[input.component-1]=true;select(input.component-1);return {component:input.component,name:data[selected].name,description:data[selected].text,isolated}}});
register({name:'set_patch_explosion',description:'Set the separation of the patch layers from assembled (0) to exploded (100).',inputSchema:{type:'object',properties:{percent:{type:'number',minimum:0,maximum:100}},required:['percent'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.percent!=='number'||!Number.isFinite(input.percent)||input.percent<0||input.percent>100)throw new Error('Percent must be between 0 and 100.');isolated=false;updateVisibility();spread(input.percent);return {percent:input.percent}}});}
